# Test queries for inserting data into the database
test_insert_recipe_table = """
    INSERT INTO Recipes (id, recipe_name, description, ingredients, serving_size, steps) VALUES
    (1, 'Spaghetti Bolognese', 'A classic Italian pasta dish', ARRAY['Spaghetti', 'Ground beef', 'Tomato sauce', 'Onion', 'Garlic', 'Olive oil', 'Basil'], 4, ARRAY['Cook spaghetti according to package instructions', 'Heat olive oil in a pan', 'Add onion and garlic, cook until soft', 'Add ground beef, cook until browned', 'Stir in tomato sauce and basil', 'Simmer for 15 minutes', 'Serve sauce over spaghetti']),
    (2, 'Chicken Curry', 'A spicy and flavorful curry', ARRAY['Chicken breast', 'Coconut milk', 'Curry powder', 'Onion', 'Garlic', 'Ginger', 'Tomato paste', 'Cilantro'], 4, ARRAY['Cut chicken into bite-sized pieces', 'Heat oil in a pot', 'Add onion, garlic, and ginger, cook until fragrant', 'Add chicken and cook until no longer pink', 'Stir in curry powder and tomato paste', 'Pour in coconut milk, bring to a boil', 'Simmer for 20 minutes', 'Garnish with cilantro before serving']),
    (3, 'Vegetable Stir Fry', 'A quick and healthy stir fry', ARRAY['Broccoli', 'Carrot', 'Bell pepper', 'Snap peas', 'Soy sauce', 'Garlic', 'Ginger', 'Sesame oil'], 2, ARRAY['Chop all vegetables into bite-sized pieces', 'Heat sesame oil in a wok', 'Add garlic and ginger, cook until fragrant', 'Add vegetables and stir-fry for 5-7 minutes', 'Pour in soy sauce and stir well', 'Cook for another 2 minutes', 'Serve hot']),
    (4, 'Pancakes', 'Fluffy and delicious pancakes', ARRAY['Flour', 'Milk', 'Egg', 'Baking powder', 'Salt', 'Sugar', 'Butter'], 4, ARRAY['Mix flour, baking powder, salt, and sugar in a bowl', 'Whisk milk and egg in another bowl', 'Combine wet and dry ingredients', 'Heat butter in a pan', 'Pour batter onto pan to form pancakes', 'Cook until bubbles form, then flip', 'Serve with syrup']),
    (5, 'Caesar Salad', 'A fresh and crunchy Caesar salad', ARRAY['Romaine lettuce', 'Caesar dressing', 'Croutons', 'Parmesan cheese', 'Chicken breast', 'Lemon juice'], 2, ARRAY['Chop romaine lettuce', 'Grill chicken breast and slice', 'Toss lettuce with Caesar dressing', 'Add croutons and Parmesan cheese', 'Top with grilled chicken', 'Drizzle with lemon juice before serving']);
    """
