CREATE TABLE wfp_food_prices (
    adm0_id VARCHAR(10),
    adm0_name VARCHAR(50),
    adm1_id VARCHAR(10),
    adm1_name VARCHAR(50),
    mkt_id VARCHAR(10),
    mkt_name VARCHAR(50),
    cm_id VARCHAR(10),
    cm_name VARCHAR(50),
    cur_id VARCHAR(10),
    cur_name VARCHAR(50),
    pt_id VARCHAR(10),
    pt_name VARCHAR(50),
    um_id VARCHAR(10),
    um_name VARCHAR(50),
    mp_month INTEGER,
    mp_year INTEGER,
    mp_price DECIMAL(10, 2),
    mp_commoditysource VARCHAR(50)
);